### ISSUE TITLE
Book List and Map Page is too Wide

### ISSUE THREAD

**Issue by Isaac-List** [Route-finder/Frontend#35]
**Describe the bug**
Book List and Map page is too wide

**To Reproduce**
1. Go to https://route-finder.netlify.app/book-list

**Expected behavior**

Page should not scroll horizontally

**Screenshots**

![Screenshot 2022-04-25 at 14-44-29 Route Finder](https://user-images.githubusercontent.com/48964096/165162721-8bce7352-b0e6-4d05-8dae-5ce65db60ebb.png)

**Additional context**
Probably a CSS issue with margins or widths.

**Comment by AlexDikelsky** [comment]
This is okay, the map is to large to fit on one page
